SELECT 
	dbo.V_Allevatori.ID_ALLEVAMENTO, 
	dbo.TIPO_LATTE.ID_TIPO_LATTE, 
	dbo.TIPO_LATTE.FATTORE_CONVERSIONE, 
	dbo.TIPO_LATTE.FLAG_INVIO_SITRA
FROM            
	dbo.V_Allevatori 
	
	INNER JOIN
    dbo.UTENTI ON dbo.V_Allevatori.ID_UTENTE = dbo.UTENTI.ID_UTENTE 
	
	INNER JOIN
    dbo.TIPO_LATTE ON dbo.UTENTI.ID_TIPO_LATTE = dbo.TIPO_LATTE.ID_TIPO_LATTE