SELECT        
	dbo.ANAGRAFE_ALLEVAMENTO.ID_ALLEVAMENTO, 
	dbo.ANAGRAFE_ALLEVAMENTO.ID_UTENTE, 
	dbo.ANAGRAFE_ALLEVAMENTO.INDIRIZZO_ALLEVAMENTO, 
	dbo.ANAGRAFE_ALLEVAMENTO.ID_COMUNE, 
    dbo.UTENTI.RAGIONE_SOCIALE, 	
	dbo.UTENTI.NOME, 
	dbo.UTENTI.COGNOME, 
	dbo.UTENTI.ID_TIPO_LATTE,
	dbo.ANAGRAFE_ALLEVAMENTO.IDSITRA_STABILIMENTO_ALLEVAMENTO, 
	dbo.ANAGRAFE_ALLEVAMENTO.CODICE_ASL,
	dbo.COMUNI.PROVINCIA, 
    dbo.COMUNI.DESCRIZIONE
FROM            

	dbo.ANAGRAFE_ALLEVAMENTO 
	
	INNER JOIN
    dbo.UTENTI ON dbo.ANAGRAFE_ALLEVAMENTO.ID_UTENTE = dbo.UTENTI.ID_UTENTE 
	
	INNER JOIN
    dbo.COMUNI ON dbo.ANAGRAFE_ALLEVAMENTO.ID_COMUNE = dbo.COMUNI.ID_COMUNE