SELECT 
	*,
	TRY_CONVERT(decimal(18,4), REPLACE(ANALISI_LATTE_VALORI.VALORE, ',', '.')) As VALORE_DECIMAL
  FROM 

    ANALISI_LATTE

    left outer join
    ANALISI_LATTE_VALORI on ANALISI_LATTE.CAMPIONE = ANALISI_LATTE_VALORI.Analisi_Id