SELECT DISTINCT 
                         
	dbo.UTENTI.NOME, 
	dbo.UTENTI.COGNOME, 
	dbo.UTENTI.INDIRIZZO, 
	dbo.UTENTI.TELEFONO,
	dbo.UTENTI.CELLULARE, 
	dbo.UTENTI.ID_UTENTE, 
	dbo.UTENTI.PIVA_CF,
	dbo.UTENTI.RAGIONE_SOCIALE,
	dbo.COMUNI.DESCRIZIONE, 
	dbo.COMUNI.PROVINCIA

FROM            

	dbo.UTENTI 
	
	INNER JOIN
    dbo.COMUNI ON dbo.UTENTI.ID_COMUNE = dbo.COMUNI.ID_COMUNE 
	
	INNER JOIN
    dbo.PROFILO ON dbo.UTENTI.ID_PROFILO = dbo.PROFILO.ID_PROFILO 
	
	CROSS JOIN
    dbo.PROFILO AS PROFILO_1

WHERE        
	(dbo.PROFILO.DESCRIZIONE_PROFILO = 'Trasportatore')