// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Eliminazione_V_Prelievi_Latte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eliminazione_V_Prelievi_Latte));
        
        string IMigrationMetadata.Id
        {
            get { return "201710101401542_Eliminazione_V_Prelievi_Latte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
