// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Aggiunta_V_Allevatori : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aggiunta_V_Allevatori));
        
        string IMigrationMetadata.Id
        {
            get { return "201710040952333_Aggiunta_V_Allevatori"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
