// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Aggiunta_V_PrelieviLatte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aggiunta_V_PrelieviLatte));
        
        string IMigrationMetadata.Id
        {
            get { return "201807311013391_Aggiunta_V_PrelieviLatte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
