// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_column_fattoreConversione_on_TipiLatte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_column_fattoreConversione_on_TipiLatte));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071110060_Add_column_fattoreConversione_on_TipiLatte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
