// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AggiuntoCampo_CUAA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiuntoCampo_CUAA));
        
        string IMigrationMetadata.Id
        {
            get { return "201807161522304_AggiuntoCampo_CUAA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
