// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Aggiornata_V_Prelievi1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aggiornata_V_Prelievi1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007010919323_Aggiornata_V_Prelievi1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
