// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModificaTabella_DISPOSITIVI_MOBILI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificaTabella_DISPOSITIVI_MOBILI));
        
        string IMigrationMetadata.Id
        {
            get { return "202004181014272_ModificaTabella_DISPOSITIVI_MOBILI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
