// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AggiuntoCodiceAllevatore_V_Allevamenti : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiuntoCodiceAllevatore_V_Allevamenti));
        
        string IMigrationMetadata.Id
        {
            get { return "202004011519589_AggiuntoCodiceAllevatore_V_Allevamenti"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
