// <auto-generated />
namespace LatteMarche.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AggiornamentoTipiColonna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiornamentoTipiColonna));
        
        string IMigrationMetadata.Id
        {
            get { return "202009211225559_AggiornamentoTipiColonna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
